"""empty message

Revision ID: f506865b57fe
Revises: 
Create Date: 2026-01-28 16:16:58.110652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f506865b57fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_coach', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('coach_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dashboard_metrics', sa.Text(), nullable=True))
        batch_op.create_foreign_key('coach', 'user', ['coach_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('dashboard_metrics')
        batch_op.drop_column('coach_id')
        batch_op.drop_column('is_coach')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
